VERSION=1.1.0-RC1
JS=jsonc -d 4 -p
DEST=/home/www/anc/LAPPS/vocab/schema
SCHEMATA=lif-schema.json container-schema.json datasource-schema.json metadata-schema.json

#.schema .json:
#	jsonc -d 4 -p -i $@
	

help:
	@echo
	@echo "Goals"
	@echo
	@echo "       all : generates all JSON Schema"
	@echo "       lif : a LIF Container"
	@echo "      data : a LAPPS Data object""
	@echo "datasource : metadata returned by DataSources"
	@echo "  metadata : metatdata returnd by WebServices"
	@echo "     clean : deletes all generated schemata"
	@echo "    upload : uploads schemata to the vocab web site"
	@echo			
			
all: lif container datasource metadata

mkdir:
	if [ ! -e schemata ] ; then mkdir schemata ; fi 

lif: mkdir
	$(JS) -o ./schemata/$@-schema-$(VERSION).json $@.schema 

data: mkdir
	$(JS) -o ./schemata/$@-schema-$(VERSION).json $@.schema 

datasource: mkdir
	$(JS) -o ./schemata/$@-schema-$(VERSION).json $@.schema 

metadata: mkdir
	$(JS) -o ./schemata/$@-schema-$(VERSION).json $@.schema 

clean:
	if [ -e schemata ] ; then rm -rf schemata ; fi

upload: $(SCHEMATA)
	./upload.sh

#token: 
#	$(JS) -i token.schema -o token.json

#lif:
#	$(JS) -i lif.schema -o lif.json
	
#get:
#	$(JS) -i get.schema -o get.schema
	
#lif: lif.json

#get: get.schema

#list: list.schema

#size: size.schema

#getmetadata: getmetadata.schema

#container: container.schema

#execute: execute.schema

